services:
  foundry:
    image: ghcr.io/felddy/foundryvtt:13
    container_name: pivot-foundry-v13
    hostname: pivot-foundry-v13
    env_file:
      - path: .env.foundry.local
        required: false
    environment:
      CONTAINER_PRESERVE_CONFIG: "false"
      FOUNDRY_HOT_RELOAD: "true"
      FOUNDRY_IP_DISCOVERY: "false"
      FOUNDRY_TELEMETRY: "false"
      FOUNDRY_VERSION: "13.351"
      TZ: America/New_York
    ports:
      - "30000:30000/tcp"
    volumes:
      - type: bind
        source: ./foundry-data
        target: /data
      - type: bind
        source: ./system.json
        target: /data/Data/systems/pivot-fantasy/system.json
        read_only: true
      - type: bind
        source: ./dist
        target: /data/Data/systems/pivot-fantasy/dist
        read_only: true
      - type: bind
        source: ./lang
        target: /data/Data/systems/pivot-fantasy/lang
        read_only: true
      - type: bind
        source: ./packs
        target: /data/Data/systems/pivot-fantasy/packs
        read_only: true
      - type: bind
        source: ./styles
        target: /data/Data/systems/pivot-fantasy/styles
        read_only: true
      - type: bind
        source: ./templates
        target: /data/Data/systems/pivot-fantasy/templates
        read_only: true
    restart: "no"
